# Adding Load Balancer Manifest Service for v3
apiVersion: v1 
kind: Service
metadata:
  name: flaskwebapp-loadbalancer
  labels:
    app: flask-webapp
    tier: frontend
spec:
  ports: # allow web traffic to the pods on port 80 using TCP
  - port: 80
    protocol: TCP
    name: http-loadbalancer
  selector: # finds all pods with given label below & load balances the traffic between pods
    app: flask-webapp
    tier: frontend
  type: LoadBalancer
---
# Deployment Manifest from v1
apiVersion: apps/v1 # Provides backwards compatibility with different k8s versions
kind: Deployment
metadata:
  name: flaskwebapp-deployment
  labels:
    app: flask-webapp
    tier: frontend
spec: # Replication controller
  replicas: 1
  selector:
    matchLabels: # Adopts labels from Pod Template below
      app: flask-webapp
      tier: frontend
  template: # Template for my pods
    metadata:
      labels: # Pod labels
        app: flask-webapp
        tier: frontend
    spec: # Single container Pod spec
      containers: 
      - name: flask-container
        image: cheesburger/k8s-flask-webapp # DockerHub image
        ports: # set port on pod
        - containerPort: 5000
